=== SoftwareEngineeringOne/webengineering/labs/lab2/xml-task_1_2/text.dtd
<!ELEMENT text (section+)>
<!ELEMENT section (title?, content)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT content (#PCDATA | bold | italic | underline)*>
<!ELEMENT bold (#PCDATA)>
<!ELEMENT italic (#PCDATA)>
<!ELEMENT underline (#PCDATA)>

<!ATTLIST title 
    font CDATA #IMPLIED
>
<!ATTLIST content 
    font CDATA #IMPLIED
>

=== SoftwareEngineeringOne/webengineering/labs/lab4/xml-task/text.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="style.css" type="text/css"?>
<!DOCTYPE text SYSTEM "text.dtd">

<text>
    <section>
        <title font="TITLE_1">Edward Snowden</title>
        <content>
            <bold>Edward Snowden</bold> ist ein <italic>US-amerikanischer Whistleblower</italic> und
            ehemaliger <italic>CIA-Mitarbeiter</italic>. Seine Enthüllungen gaben Einblicke in das
            Ausmaß der weltweiten Überwachungs- und Spionagepraktiken von
            Geheimdiensten – überwiegend jenen der Vereinigten Staaten und
            Großbritanniens. Diese lösten im Sommer 2013 die NSA-Affäre aus.
        </content>
    </section>
    <section>
        <content>
            Er wurde dafür mehrfach von nichtstaatlichen Organisationen
            ausgezeichnet und für den Friedensnobelpreis nominiert.
        </content>
    </section>
</text>
